services:
  reader:
    image: ghcr.io/psomani16k/reader:latest
    container_name: reader 
    restart: unless-stopped
    ports:
      - "5001:6969"
    volumes:
      - ./epubs:/epubs
      - ./html:/html
      - ./data:/data
    # Optional: set user permissions to match your local user
    user: "1000:1000"
